# Generated by Django 3.0.7 on 2020-07-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elibrary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('student_rollNo', models.CharField(max_length=100)),
                ('book_name', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('feedback', models.CharField(max_length=255)),
            ],
        ),
    ]
